graphql:
  spqr:
    gui:
      enabled: true
spring:
  r2dbc:
    url: r2dbc:h2:file://~/~/testdb2
    username: sa
    password: password

  flyway:
    url: jdbc:h2:file:~/testdb2
    user: sa
    password: password
    enabled: true
    locations: classpath:db/migration


  security:
    oauth2:
      resourceserver:
        jwt:
          issuerUri: https://dev-6053964.okta.com/oauth2/default
          jwk-set-uri: https://dev-6053964.okta.com/oauth2/default/v1/keys


okta:
  oauth2:
    client-secret: AIew68aO_XNNYIcoaX-qm6hRPM_p-O2lm36r-316
    client-id: 0oaqsdj57s80mcWr85d6
    issuer: https://dev-6053964.okta.com/oauth2/default
    groups-claim: roles

